-- SELECT * FROM UTMED_CLARITY0.ALERT@SOURCE.MI WHERE ROWNUM <= 20;

-- Earliest encounter month end for each patient
--/
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE TMP_PAT_DATE00';
   EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

CREATE TABLE TMP_PAT_DATE00 AS (
        SELECT PAT_ID,MIN(LAST_DAY(CONTACT_DATE)) FIRST_CONTACT 
        FROM UTMED_CLARITY0.PAT_ENC@SOURCE.MI
        GROUP BY PAT_ID
);

-- Each calendar month for each patient between their earliest encounter and now

--INTO ##PAT_DATE01
WITH q0 AS (
SELECT DATE'2000-01-01' + level - 1 DT
FROM DUAL CONNECT BY level <= ( SYSDATE - DATE'2000-01-01' + 1))
SELECT * FROM q0 WHERE EXTRACT(DAY FROM DT) = 1;
--INNER JOIN ##PAT_DATE00 pd ON dd.MONTH_END_DT BETWEEN FIRST_CONTACT AND GETDATE()


